source = $HOME/.cache/wal/colors-hyprland.conf

$fontFamily = JetBrainsMono Nerd Font

# resolved using font.sh when selecting style
$resolve.font=Anurati|https://font.download/dl/font/anurati.zip
$resolve.font=Inter|https://github.com/rsms/inter/releases/download/v4.1/Inter-4.1.zip

background {
    monitor =
    path = $HOME/.current_wallpaper
    blur_size = 4
    blur_passes = 3
    noise = 0.0117
    contrast = 1.3000
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

# DAY
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A" | sed 's/./& /g' | tr '[:lower:]' '[:upper:]')"
    color = $color6
    font_size = 110
    font_family = Anurati bold
    position = 0, 100
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%B %d")"
    color = $color7
    font_size = 35
    font_family = $font_family Thin
    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%-I:%M %p")"
    color = $color6
    font_size = 20
    font_family = $font_family
    position = 0, 150
    halign = center
    valign = bottom
}

# INPUT FIELD
input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1
    outer_color = $color0
    inner_color = $color0
    font_color = $color6
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Password...</i>
    hide_input = false
    rounding = -1
    check_color = $color6
    fail_color = rgba(FF0000FF)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = true
    position = 0, 80
    halign = center
    valign = bottom
}

# User tag
label {
    monitor =
    text =   $USER
    color = $color7
    font_size = 20
    font_family = Inter Display Medium
    position = 0, 30
    halign = center
    valign = bottom
}

# Battery Status
label {
    monitor =
    text = cmd[update:5000] $BATTERY_ICON
    color = $color6
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = -1%, 1%
    halign = right
    valign = bottom
}
