source = $HOME/.cache/wal/colors-hyprland.conf

# GENERAL
general {
    no_fade_in = true
    no_fade_out = true
    disable_loading_bar = false
    hide_cursor = true
    immediate_render = true
}

# BACKGROUND
background {
    monitor =
    path = $HOME/.current_wallpaper
    color = $color0
    blur_passes = 1
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.8916
    vibrancy_darkness = 0.0
}

# Date-Time Label
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d - %I:%M %p")"
    color = $color6
    font_size = 15
    position = 0, 45%
    halign = center
    valign = center
}

# User-Box
shape {
    monitor =
    size = 15%, 3%
    color = $color0
    rounding = 0
    border_size = 2
    border_color = $color0
    rotate = 0
    position = 35%, 5%
    halign = left
    valign = center
    zindex = 5
}

# Authenticate Box
shape {
    monitor =
    size = 35%, 10%
    color = rgba(0, 0, 0, 0)
    rounding = 0
    border_size = 2
    border_color = $color7
    rotate = 0
    position = 0, 0
    halign = center
    valign = center
}

# Authenticate Message
label {
    monitor =
    text =  cmd[] source /etc/os-release ; echo "Authenticate into ${PRETTY_NAME:-$NAME}"
    color = $color7
    font_size = 11
    position = -7.5%, 5%
    halign = center
    valign = center
    zindex = 5
}

# Username Label
label {
    monitor =
    text = <b>Username: $USER</b>
    color = $color7
    font_size = 11
    position = 34%, 2%
    halign = left
    valign = center
    zindex = 1
}

# Password Label
label {
    monitor =
    text = <b>Password:</b>
    color = $color7
    font_size = 11
    position = 34%, -1%
    halign = left
    valign = center
    zindex = 5
}

# Input Field
input-field {
    monitor =
    size = 15%, 5%
    outline_thickness = -1
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = false
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0)
    font_color = $color6
    fade_on_empty = false
    placeholder_text =
    hide_input = false
    position = 38.4%, -1%
    halign = left
    valign = center
}

# Battery Icon
label {
    monitor =
    text = cmd[update:5000] $BATTERY_ICON
    color = $color6
    font_size = 20
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 1%, 1%
    halign = left
    valign = bottom
    zindex = 5
}

# Weather
label {
    monitor =
    text = cmd[update:18000000] $WEATHER_CMD
    color = $color6
    font_size = 10
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 3%, 1.5%
    halign = left
    valign = bottom
    zindex = 5
}

# Layout
label {
    monitor =
    text = $LAYOUT
    color = $color6
    font_size = 10
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 0%, 1.5%
    halign = right
    valign = bottom
    zindex = 5
}
