source = $HOME/.cache/wal/colors-hyprland.conf

# Local Variables
$fontFamily = JetBrainsMono Nerd Font
# $fn_greet=echo "Good $(date +%H | awk '{if ($1 < 12) print "Morning"; else if ($1 < 18) print "Afternoon"; else print "Evening"}'), ${USER}"
$fn_greet=echo "Good $(date +%H | awk '{if ($1 < 12) print "Morning"; else if ($1 < 18) print "Afternoon"; else print "Evening"}'), Priyesh Mishra"

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# BACKGROUND
background {
    monitor =
    path = $HOME/.current_wallpaper
    blur_passes = 2
}

# TIME
label {
  monitor =
  text = cmd[update:1000] date +"%H:%M"
  color = $color6
  font_size = 90
  font_family = $fontFamily Bold
  position = -30, 0
  halign = right
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $color7
  font_size = 25
  font_family = $fontFamily
  position = -30, -150
  halign = right
  valign = top
}

# USER AVATAR
image {
    monitor =
    path = $HOME/Pictures/profile icon/yoshimitshu.icon
    # path = $HOME/Pictures/profile icon/geass.icon
    size = 250
    # rounding = 500
    border_size = 6
    border_color = $color6
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1
    outer_color = $color0
    inner_color = $color0
    font_color = $color6
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Input Password...</i>
    hide_input = false
    rounding = -1
    check_color = $color6
    fail_color = rgba(FF0000FF)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = true
    position = 0, 80
    halign = center
    valign = bottom
}

# USER Greeting
label {
    monitor =
    text = cmd[update:60000] $fn_greet
    color = $color7
    font_size = 25
    font_family = $fontFamily Bold Italic
    position = 0, -16%
    halign = center
    valign = center
}

# MPRIS TEXT
label {
    monitor =
    text = cmd[update:1000] playerctl metadata title 2>/dev/null | sed 's/^/  /'
    color = $color7
    font_family = $fontFamily
    font_size = 15
    position = 0, 0
    halign = center
    valign = bottom
}

# to add mpris here

$LAST_PLAYER="$(playerctl -l | tail -n1)"

# Next button
label {
    monitor =
    text = cmd[update:1000] { playerctl status -p $LAST_PLAYER 2>/dev/null | grep -q "Playing" ;} && echo "󰒭"
    onclick = playerctl -p $LAST_PLAYER next
    color = $color7
    font_size = 20
    font_family = $fontFamily Bold
    position = 2%, -13 %
    halign = center
    valign = center
}

# Prev button
label {
    monitor =
    text = cmd[update:1000] { playerctl status -p $LAST_PLAYER 2>/dev/null | grep -q "Playing" ;} && echo "󰒮"
    onclick = playerctl -p $LAST_PLAYER previous && pkill -u $USER -SIGUSR2 hyprlock
    color = $color7
    font_size = 20
    font_family = $fontFamily Bold
    position = -2%, -13 %
    halign = center
    valign = center
}

# Play/Pause button
label {
    monitor =
    text = cmd[update:1000] player=$LAST_PLAYER; [ -z "$player" ] && echo "" || (playerctl status -p "$player" 2>/dev/null | grep -q '^Playing$' && echo "⏸" || echo "▶")
    onclick = playerctl -p $LAST_PLAYER play-pause
    color = $color7
    font_size = 20
    font_family = $fontFamily Bold
    position = 0, -13 %
    halign = center
    valign = center
}

# Battery Percentage
label {
    monitor =
    text = cmd[update:10000] upower -i $(upower -e | grep BAT) | awk '/percentage/ {print $2}'
    color = $color7
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = -1%, 1%
    halign = right
    valign = bottom
}
