$fontFamily = IBM Plex Sans
$resolve.font=IBM Plex Sans|https://github.com/IBM/plex/releases/download/%40ibm%2Fplex-sans%401.1.0/ibm-plex-sans.zip

source = $HOME/.cache/wal/colors-hyprland.conf

# GENERAL
background {
    monitor =
    path = $HOME/.current_wallpaper   # only png supported for now
    blur_size = 5
    blur_passes = 0
    noise = 0.0117
    contrast = 1.3000
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

# Current time
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H") </big></b>"
    color = $color6
    font_size = 180
    font_family = $fontFamily Medium 10
    position = 0, 80
    halign = center
    valign = center
}
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%M") </big></b>"
    color = $color6
    font_size = 180
    font_family = $fontFamily Medium 10
    position = 0, -120
    halign = center
    valign = center
}
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%d %b") </big></b>"
    color = $color7
    font_size = 20
    font_family = $fontFamily Medium 10
    position = 0, -230
    halign = center
    valign = center
}
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%A") </big></b>"
    color = $color7
    font_size = 20
    font_family = $fontFamily Medium 10
    position = 0, -250
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 1.00
    dots_center = true
    outer_color = $color0
    inner_color = $color0
    font_color = $color6
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, 60
    halign = center
    valign = bottom
}

# Battery Status
label {
    monitor =
    text = cmd[update:5000] $BATTERY_ICON
    color = $color7
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = -1%, 1%
    halign = right
    valign = bottom
}

# Keyboard Layout
label {
    monitor =
    text = $LAYOUT
    color = $color7
    font_size = 20
    font_family = $fontFamily
    position = -2%, 1%
    halign = right
    valign = bottom
}
