source = $HOME/.cache/wal/colors-hyprland.conf


monitor=,preferred,auto,1

dwindle {
  pseudotile = yes
  preserve_split = yes
  special_scale_factor = 0.8
}

master {
  new_on_top=1
  mfact = 0.5
}

general {
    gaps_in = 5
    gaps_out = 20

    border_size = 2

    col.active_border = $color6
    col.inactive_border = $color0

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle

    snap { # snapping for floating windows
        enabled = true
    }
}

decoration {
    rounding = 10
    rounding_power = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 1.0

    dim_special = 0.3
    fullscreen_opacity = 1

    shadow {
        enabled = true
        range = 25
        render_power = 3
        color = $color6
        # color = rgba(1a1a1aee)
    }
    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 3
        passes = 1
        special = true
        vibrancy = 0.1696
        ignore_opacity = true
        new_optimizations = true
    }
}

input {
  kb_layout=us
  kb_variant=
  kb_model=
  kb_options=
  kb_rules=

  # repeat_rate=50
  repeat_delay = 150

  accel_profile = flat
  numlock_by_default = true

  left_handed=0
  follow_mouse=1
  sensitivity = 1
  float_switch_override_focus=0

  touchpad {
    disable_while_typing=1
    natural_scroll=0
    clickfinger_behavior=0
    middle_button_emulation=1
    tap-to-click=1
    drag_lock=0
   }
}

gestures {
    gesture = 3, horizontal, workspace
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  mouse_move_enables_dpms = true
  vrr = 2
  enable_swallow = true
  # no_direct_scanout = true #for fullscreen games
  focus_on_activate = false
  swallow_regex = ^(kitty)$
}

#Could help when scaling and not pixelating
xwayland {
    force_zero_scaling = true
}

ecosystem {
  # no_update_news = true
}
