
# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█


# ------------------------------------------------------------------------------
# Misc.
windowrule = match:class ^org\.kde\.dolphin$, center on
windowrule = match:class ^org\.kde\.kdeconnect\.daemon$, size 300 170, tile off
windowrule = match:initial_title ^(GL.*)$, float on

# Brave apps forced tiled
# windowrule = match:class ^brave-browser$, tile on

# Flameshot
windowrule = match:class ^flameshot$, float on

# ------------------------------------------------------------------------------

# Fix file chooser dialogs opening off-screen
# windowrule = float true,match:tag portal-dialogs
# windowrule = center on,match:tag portal-dialogs


# idle_inhibit rules
windowrule = match:class vlc|mpv|celluloid, idle_inhibit fullscreen
windowrule = idle_inhibit fullscreen, match:class ^(.*[Ss]potify.*)$
windowrule = idle_inhibit fullscreen, match:class ^(.*brave-browser.*)$|^(.*chromium.*)$|^(.*zen.*)$

# Picture-in-Picture
windowrule = tag +pip, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture).*$
windowrule = float true,            match:tag pip
windowrule = pin true,              match:tag pip
windowrule = keep_aspect_ratio true,match:tag pip
windowrule = size 25%,              match:tag pip
windowrule = move 73% 72%,          match:tag pip

# core applications
windowrule = float true,match:class = ^(blueman-manager|pavucontrol-qt|com\.gabm\.satty|vlc|kvantummanager|qt[56]ct|nwg-(look|displays)|org\.kde\.ark|org\.pulseaudio\.pavucontrol|blueman-manager|nm-(applet|connection-editor)|org\.kde\.polkit-kde-authentication-agent-1|console-dropdown)$
windowrule = float true,match:class brave-nngceckbapebfimnlniiiahkandclblb-Default # Bitwarden

# dolphin popups
windowrule = float true,match:class = ^(org\.kde\.dolphin)$
windowrule = float true,match:title = ^(Progress Dialog — Dolphin|Copying — Dolphin)$

# common popups
windowrule = float true,center true,match:title = ^(Choose Files|Save As|Confirm to replace files|File Operation Progress|Open|Authentication Required|Add Folder to Workspace|File Upload.*|Choose wallpaper.*|Library.*|.*dialog.*)$
windowrule = float true,center true,match:initial_title ^(Open File|Volume Control|Save As.*)$
windowrule = float true,center true,match:class ^(.*dialog.*|[Xx]dg-desktop-portal-gtk)$
windowrule = float true,center true,match:class = ^(org\.freedesktop\.impl\.portal\.desktop\.(hyprland|gtk)|[Xx]dg-desktop-portal-gtk)$

# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

layerrule = blur true, match:namespace ^(rofi|notifications|swaync-(notification-window|control-center)|logout_dialog|waybar)$
layerrule = ignore_alpha true, match:namespace ^(rofi|notifications|swaync-(notification-window|control-center)|logout_dialog|waybar|selection)$
layerrule = no_anim true, match:namespace selection
