
# Apps → workspaces
windowrule = match:class ^Notion$, workspace 1
windowrule = match:class ^notion-calendar-electron$, workspace 2

windowrule = match:class ^(p3x-onenote|obsidian)$, workspace 3

windowrule = match:class ^(org\.wezfurlong\.wezterm|kitty)$, workspace 4

windowrule = match:class ^(spotify|com\.github\.th_ch\.youtube_music)$, workspace 5

windowrule = center on,match:class ^(steam|steam_app_.*|itch|heroic|net\.lutris\.Lutris)$, workspace 10
