
# workspace 1 -> Notion && Notion-calendar
windowrule = match:class ^Notion$, workspace 1
windowrule = match:class ^notion-calendar-electron$, workspace 1

# workspace 2 -> OneNote && Obsidian
windowrule = match:class ^(p3x-onenote|obsidian)$, workspace 2

# workspace 3 -> Kitty && wezterm
windowrule = match:class ^(org\.wezfurlong\.wezterm|kitty)$, workspace 3

# workspace 4 -> spotify && YOutube-Music
windowrule = match:class ^(spotify|com\.github\.th_ch\.youtube_music)$, workspace 4

# workspace 5 -> Brave-Browser
windowrule = match:class ^(brave-browser)$, workspace 5

# workspace 10 -> Steam && Lutris && Itch && Heroic
windowrule = center on,match:class ^(steam|steam_app_.*|itch|heroic|net\.lutris\.Lutris)$, workspace 10
