return {
  'folke/trouble.nvim',
  event = 'VeryLazy',
  keys = {
    { '<leader>dd', '<cmd>Trouble diagnostics toggle<cr>',            desc = 'Diagnostics (Trouble)' },
    -- { '<space>dx',  '<cmd>Trouble diagnostics toggle filter.buf=0<cr>', desc = 'Buffer Diagnostics (Trouble)' },
    { '<leader>ds', '<cmd>Trouble symbols toggle<cr>',                desc = 'Symbols (Trouble)' },
    { '<leader>dr', '<cmd>Trouble lsp toggle win.position=right<cr>', desc = 'LSP References / Definitions (Trouble)' },
    { '<leader>dl', '<cmd>Trouble loclist toggle<cr>',                desc = 'Location List (Trouble)' },
    { '<leader>dq', '<cmd>Trouble qflist toggle<cr>',                 desc = 'Quickfix List (Trouble)' },
    { '<leader>dt', '<cmd>Trouble todo<cr>',                          desc = 'TODOs (Trouble)' },
  },
  opts = {
    focus = true,
    auto_close = false,
    auto_open = false,
    auto_preview = true,
    auto_refresh = true,
    auto_jump = false,
    restore = true,
    follow = true,
    indent_guides = true,
    max_items = 200,
    multiline = true,
    pinned = false,
    warn_no_results = true,
    open_no_results = false,
  },
}
