return {
  'folke/trouble.nvim',
  event = 'VeryLazy',
  keys = {
    { '<space>xx', '<cmd>Trouble diagnostics toggle<cr>', desc = 'Diagnostics (Trouble)' },
    -- { '<space>xX', '<cmd>Trouble diagnostics toggle filter.buf=0<cr>', desc = 'Buffer Diagnostics (Trouble)' },
    { '<space>xs', '<cmd>Trouble symbols toggle<cr>',     desc = 'Symbols (Trouble)' },
    {
      '<space>xr',
      '<cmd>Trouble lsp toggle win.position=right<cr>',
      desc = 'LSP Definitions / references / ... (Trouble)',
    },
    { '<space>xl', '<cmd>Trouble loclist toggle<cr>', desc = 'Location List (Trouble)' },
    { '<space>xq', '<cmd>Trouble qflist toggle<cr>',  desc = 'Quickfix List (Trouble)' },
    { '<space>xt', '<cmd>Trouble todo<cr>',           desc = 'Todo Trouble' },
  },
  opts = {
    focus = true,
    auto_close = false,
    auto_open = false,
    auto_preview = true,
    auto_refresh = true,
    auto_jump = false,
    restore = true,
    follow = true,
    indent_guides = true,
    max_items = 200,
    multiline = true,
    pinned = false,
    warn_no_results = true,
    open_no_results = false,
  },
}
